import Header from 'components/headerComponents';
import Head from 'next/head';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Google Clone</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* Header */}
      <Header />
      {/* Body */}

      {/* Footer */}
    </div>
  );
}
