import Body from 'components/home-page/bodyComponents';
import Footer from 'components/home-page/footerComponents';
import Header from 'components/home-page/headerComponents';
import Head from 'next/head';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Google Clone</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* Header */}
      <Header />

      {/* Body */}
      <Body />

      {/* Footer */}
      <Footer />
    </div>
  );
}
